version: 0.2
phases:
  install:
    runtime-versions:
      nodejs: 10
    commands:
      - npm install
      - npm start
  build:
    commands:
      
      # run the build
      #- ng build --prod
artifacts:
  files:
    # bundle everything as a build artifact, except hidden files
    - '**/*'
